# Generated by Django 3.1.2 on 2020-10-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='content',
            new_name='point',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='label',
        ),
        migrations.AddField(
            model_name='movie',
            name='label',
            field=models.ManyToManyField(to='z_web.MovieLabel', verbose_name='movie label'),
        ),
    ]
