# Generated by Django 3.1.2 on 2020-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_web', '0002_auto_20201029_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(default='http://', verbose_name='movie url'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='douban',
            field=models.URLField(default='http://', verbose_name='douban comment'),
        ),
    ]
