# Generated by Django 3.1.2 on 2020-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_web', '0003_auto_20201029_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='head_pics',
            field=models.FileField(default='abc', upload_to='web/head_pics/', verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='douban',
            field=models.URLField(default='http://', verbose_name='豆瓣影评'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='label',
            field=models.ManyToManyField(to='z_web.MovieLabel', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_url',
            field=models.URLField(default='http://', verbose_name='链接'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=50, verbose_name='电影名称'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='point',
            field=models.CharField(max_length=255, verbose_name='观点'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='up_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='validity',
            field=models.CharField(max_length=255, verbose_name='电影简介'),
        ),
    ]
