# Generated by Django 3.1.2 on 2020-11-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('z_web', '0004_auto_20201116_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='visual_guide',
            field=models.FileField(blank=True, null=True, upload_to='common/visual_guide', verbose_name='解说视频'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='head_pics',
            field=models.FileField(upload_to='common/head_pics/', verbose_name='图片'),
        ),
    ]
